name: coin_guardian
description: "A new Flutter project."
publish_to: 'none'  # Prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  http: ^0.13.3
  cupertino_icons: ^1.0.6
  otp: ^3.1.4
  qr_flutter: ^4.0.0
  flutter_spinkit: ^5.0.0
  flutter_secure_storage: ^5.0.3
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.3.1
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/crypto_icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
